import {
    GEST_LIFE_PUBLIC_FIREBASE_API_KEY,
    GEST_LIFE_PUBLIC_FIREBASE_AUTH_DOMAIN,
    GEST_LIFE_PUBLIC_FIREBASE_PROJECT_ID,
    GEST_LIFE_PUBLIC_FIREBASE_STORAGE_BUCKET,
    GEST_LIFE_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    GEST_LIFE_PUBLIC_FIREBASE_APP_ID,
    GEST_LIFE_PUBLIC_FIREBASE_MEASUREMENT_ID
  } from '@env';


export const firebaseConfig = {
    apiKey: GEST_LIFE_PUBLIC_FIREBASE_API_KEY,
    authDomain: GEST_LIFE_PUBLIC_FIREBASE_AUTH_DOMAIN,
    projectId: GEST_LIFE_PUBLIC_FIREBASE_PROJECT_ID,
    storageBucket: GEST_LIFE_PUBLIC_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: GEST_LIFE_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    appId: GEST_LIFE_PUBLIC_FIREBASE_APP_ID,
    measurementId: GEST_LIFE_PUBLIC_FIREBASE_MEASUREMENT_ID
}
